packages:
  - apps/*
  - packages/*
  - tools/*

catalogMode: prefer

catalog:
  "@types/node": ^24
  typescript: ^5
  vite: npm:@voidzero-dev/vite-plus-core@latest
  vitest: npm:@voidzero-dev/vite-plus-test@latest
  vite-plus: latest
  react: ^19
  react-dom: ^19
  "@types/react": ^19
  "@types/react-dom": ^19
  "@vitejs/plugin-react": latest
  tailwindcss: ^4
  "@tailwindcss/vite": ^4
  "@monaco-editor/react": ^4.7
  "@supabase/supabase-js": ^2
  class-variance-authority: ^0.7
  clsx: ^2
  lucide-react: latest
  tailwind-merge: ^2
  tw-animate-css: ^1
overrides:
  vite: "catalog:"
  vitest: "catalog:"
peerDependencyRules:
  allowAny:
    - vite
    - vitest
  allowedVersions:
    vite: "*"
    vitest: "*"
